# Site settings
title: SPEL
subtitle: Space and Planetary Exploration Laboratory
description: >
  Space and Planetary Exploration Laboratory (SPEL) was built in 2011 in the Electrical Engineering Department of the 
  University of Chile to serve as the headquarters of the design, construction, development, and operation of the first
  Chilean nanosatellite, SUCHAI. Since that year, many students have contributed to the SUCHAI project and others, extending 
  the research areas of the laboratory.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
email: spel@ing.uchile.cl
logo: img/logos/spel.svg
header-image:
   #image: img/bg-astronaut.jpg
   image: img/sats.jpg
   #attrib: Photo by Niketh Vellanki on Unsplash
   #image: img/constelacion-UCH.jpg

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 636b70
  secondary: d42e12
  secondary-dark: d42e12

# Social
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/spel
  - title: envelope
    url: mailto:spel@ing.uchile.cl
  - title: github
    url: https://github.com/spel-uchile/


# Custom settings
# Uses font awesome icons name, without 'fa-' prefix. Examples:
#  space-shuttle user-astronaut globe-americas satellite meteor satellite-dish
# Use '>' after description:, so Jekyll will ignore the line breaks.
research:
  - name: Space exploration
    icon: space-shuttle
    description: >
      The laboratory's team collaborates with other partners to explore space by developing space
      missions taking advantage of miniaturized satellites. The research is focused on the space and
      planetary environments that might support different ecosystems in space.

  - name: Planetary research
    icon: globe-americas
    description: >
      The laboratory's team collaborates with other partners to study earth environment, in particular
      in extreme environments. This work is not only to contribute in the understanding of life in our
      planet, but also as to use that knowledge for supporting the search and/or maintenance of life
      either in space or in other celestial bodies. 

  - name: Space technology
    icon: satellite
    description: >
      The laboratory´s team is devoted to contribute in space studies by developing instrumentation, 
      on ground calibration, testing sites in extreme environments, space and on-ground communication
      solutions,  technology for miniaturized-satellite, etc.  to support space missions.

partners:
  - name: Universidad de Chile
    short:  UCH
    logo: uchile.png
    url: https://uchile.cl

  - name: Universidad de Santiago de Chile
    short:  USACH
    logo: usach.png
    url: https://usach.cl

  - name: Plasma and Nuclear Fusion Group
    short: CCHEN
    logo: cchen.png
    url: https://www.cchen.cl/

  - name: Exploration and Ore Deposit Modeling
    short: AMTC
    logo: amtc.png
    url: http://www.amtc.cl/

  - name: Fault Diagnosis & Failure Prognosis
    short: FDFP
    logo: die.png
    url: https://www.cec.uchile.cl/~morchard/

  - name: Millimeter Wave Laboratory
    short: MWL
    logo: calan.jpg
    url: http://www.das.uchile.cl/lab_mwl/

  - name: Photonic Laboratory
    short: PHOTONICS
    logo: photonics.jpg
    url: http://www.raig.uchile.cl/grupos/photonics

  - name: Laboratory of Mechanical Vibrations and Rotordynamics
    short: LMVR
    logo: lvmr.png
    url: http://www.lvmr.cl/

  - name: Wireless Networking Research Group
    short: WiNetGroup
    logo: winet.png
    url: http://winetgroup.die.cl/

  - name: Laboratory for Space Weather
    short:
    logo: spaceweather.gif
    url: https://ccc.ciencias.uchile.cl/climaespacial/index.php

#  - name: Molecular electronics Laboratory
#    short:
#    logo:
#    url:

  - name: Intelligent Software Construction Laboratory
    short: ISCLab
    logo: iscl.png
    url: https://isclab.dcc.uchile.cl/

  - name: Agencia Nacional de Investigación y Desarrollo
    short: ANID
    logo: anid.png
    url: https://www.anid.cl/

  - name: Facultad de Ciencias Fisicas y Matematicas
    short: FCFM
    logo: fcfm.png
    url: http://ingenieria.uchile.cl/
    
  - name: ESATAN-TMS
    short: ESATAN-TMS
    logo: esatan.png
    url: https://www.esatan-tms.com/

satellites:
  - name: SUCHAI 1
    about: >
      First Chilean made CubeSat developed by students at the University of Chile and launched into space in June 2017.
      Its goal was to study the ionosphere.
    img: suchai1.jpg
    url:

  - name: SUCHAI 2 & 3
    about: >
      Two 3U CubeSats to study ionosphere, magnetosphere and light pollution over the north of Chile.
    img: suchai2.jpg
    url:

  - name: PlantSat
    about: >
      Its goal is to study in low earth orbit the growth of a suitable plant, replicating the conditions that life will
      experience on Mars’ surface.
    img: plantsat.jpg
    url: https://plantsat.spel.cl/

projects:
  - name: Low Cost Reaction Wheel
    about: >
      For this project a recycled BLDC motor from old HDD was used for which an optimal shape and sized flywheel
      was develop. DRV10987 driver is used for speed control. Actual Engineering Model integrated as 3axis PC104 Std.
      PCB using I2C for communication.
    img: reactionwheel.jpg
    url: https://github.com/gdiazh/DRV10987_Firmware

  - name: SUCHAI Flight Software
    about: >
      Open source, modular and extensible nano-satellite flight software. Flight proven in the SUCHAI I CubeSat.
      Portable to FreeRTOS and GNU/Linux.
    img: flightsoftware.jpg
    url: https://github.com/spel-uchile/SUCHAI-Flight-Software

  - name: Flight software architecture
    about: >
      The satellite flight software is a complex and crucial component. As such, assessing its overall quality is
      essential to prevent unexpected behavior and failure. We employ sophisticated visualizations and fuzz testing techniques
      to ensure its internal quality and robustness.
    img: flightsoftware2.jpg
    url: https://data.spel.cl/

  - name: Low-cost localization system for a femto-satellite constellation
    about: >
      Low cost localization system that consist on using CubeSats with GPS as a reference for the femto-satellites.
      The femto-satellites estimate their position online using a Kalman filter and the TDOA of beacons sent by the
      CubeSats.
    img: femtoLoc.jpg
    url: https://github.com/spel-uchile/FOD

  - name: Variable Thrust Profile by Sequential Pulses of an Array of Solid Propellant Engines
    about: >
      Considering that the CubeSat technology can play an important role in future planetary exploration missions, the
      design of a propulsion system for the landing process of a pseudo 6U nanosatellites is formulated.
    img: thruster.jpg
    url:

  - name: Ultra-low-cost Star Tracker for Attitude Determination
    about: >
      A Star Tracker platform in which the sub-arcminutes precision can be achieved at an ultra-low-cost, filling a
      technological gap for CubeSats. This platform is based on open source astronomy software, the Raspberry Pi 3 B+,
      and its camera.
    img: star_tracker.jpg
    url: https://github.com/spel-uchile/Star_Tracker

  - name: Pypredict
    about: >
      Real-time satellite tracker and orbit propagator. This software can simulate deployments of one satellite from
      another, move forward and backward in time, show the night-day terminator, among other features. It is used as
      a simulation platform.
    img: pypredict.jpg
    url: https://github.com/spel-uchile/Pypredict
    
  - name: Estimation of ionospheric total electron
    about: >
      Estimation of ionospheric TEC and generation of ionospheric maps to study ionospheric disturbance sources, such 
      as geomagnetic storms, solar terminator, solar flares, solar eclipses, thunderstorm/lightning, tropical cyclones, 
      earthquakes, volcanic eruption, tsunamis, rocket launches, etc.
    img: tecstorm.png
    url: 

team:
  - name: Marina Stepanova
    degree: Ph.D Physics
    role: Associate professor
    img: mstepanova.jpg
    url: https://fisica.usach.cl/users/marina

  - name: Marcos Diaz
    role: Associate professor
    degree: Ph.D. Electrical Egineering
    img: mdiaz.jpg
    url: http://ingenieria.uchile.cl/facultad/cuerpo-academico/92407/ingenieria-electrica?qui_id=13058

  - name: Alexandre Bergel
    degree: Ph.D. Computer Sciences
    role: Associate professor
    img: abergel.jpg
    url: http://bergel.eu/

  - name: Marcos Orchard
    degree: Ph.D. Electrical and Computer Engineering
    role: Associate professor
    img: morchard.jpg
    url: https://www.cec.uchile.cl/~morchard/
    
  - name: César Fuentes
    role: Associate professor
    degree: Ph.D. in Astronomy
    img: cfuentes.jpg
    url: http://www.cata.cl/investigador_en.php?id=107

  - name: Carlos Gonzalez
    role: Ph.D. Student
    degree: Ph.D.(c) Electrical Engineering
    img: cgonzalez.jpg
    url: https://www.linkedin.com/in/carlosgonzalezcortes/?locale=en_US

  - name: Gustavo Díaz
    degree: Electrical Engineer
    role: Engineer
    img: gdiaz.jpg
    url: https://cl.linkedin.com/in/gustavo-diaz-ingeniero-die

  - name: Tamara Gutierrez
    degree: Computer Sciences
    role: Ms.C. Student
    img: tgutierrez.jpg
    url:

  - name: Matías Vidal
    degree: Electrical Engineer
    role: Ph.D. Electrical Engineering
    img: mvidal.jpg
    url:

  - name: Alex Becerra
    degree: Electrical Engineer
    role: Engineering
    img: abecerra.jpg
    url:

  - name: Elias Obreque
    degree: Aerospace engineering
    role: Ph.D.(c) Electrical Engineering
    img: eobreque.jpg
    url: https://www.linkedin.com/in/elias-obreque-3b1b67106/

  - name: Samuel Gutierrez
    degree: Physics Engineer
    role: Ph.D. Electrical Engineering
    img: sgutierrez.jpg
    url:

  - name: Camilo Rojas
    degree: M.Sc. Computer Sciences
    role: Engineering
    img: crojas.jpg
    url:

  - name: Mariana Salinas
    degree: Electrical Engineer
    role: Undergrad student
    img: msalinas.jpg
    url:
    
  - name: Juan Carlos Valdés
    degree: Telecommunications Engineer
    role: Ph.D. Electrical Engineering
    img: jcvaldes.png
    url:
    
  - name: Julian Barra
    degree: Mechanical Engineer
    role: Engineering
    img: jbarra.jpg
    url:
    
  - name: Rodrigo Muñoz
    degree: Electrical Engineer
    role: Ph.D. Student
    img: rmuñoz.jpg
    url:
    
  - name: Gerardo Peña
    degree: Electrical Engineer
    role: Ph.D. Student
    img: gpena.jpeg
    url:
    
  - name: Javier Rojas
    degree: Electrical Engineer
    role: Engineering
    img: profile.jpg
    url:

  - name: Cristóbal Garrido
    degree: Mechanical Engineer
    role: Engineering
    img: cgarrido.jpg
    url: 

    name: Yohadne Stable
    degree: Information Sciences
    role: Information Management
    img: 
    
alumni:
  - name: Cristóbal Garrido
    degree: Mechanical Engineer
    role: Engineering
    img: cgarrido.jpg
    url: 

publications:
 Papers:

   J.C. Valdés-Abreu, M.A. Díaz, M Bravo, and Y. Stable-Sanchez, "IonosphericTotal Electron Content Changes during the 15 February 2018 and 30 April 2022 Solar Eclipses over South America and Antarctica", Remote Sensing  Volume 15 Issue 19, 3 October 2023,  EISSN 2072-4292</li>
   <li>A. Avila, M.A. Díaz, F. Pizarro "Circular Polarized 3D-Printed Enclosed Twist Dielectric Resonator Antenna" 2023 IEEE International Symposium on Antennas and Propagation and USNC-URSI Radio Science Meeting (USNC-URSI), Pages 701-702, http://dx.doi.org/10.1109/USNC-URSI52151.2023.10237529</li>
   S.Díaz, M. A. Díaz, E. Rajo-Iglesias, "Circular polarized 3D-printed cylindrical DRA using parasitic dielectric helix" SCIENTIFIC REPORTS	SCOPUS/UCH/VID, July 2023, http://dx.doi.org/10.1038/s41598-023-39098-2</li>
   <li>J. Pedreros, A. Becerra, J. Rojas, C. Pavez , "Design and Stability Analysis of a Digital Automatic Power Control Based on a PI Controller for Laser Drivers", May 2023, ISI/SCOPUS/UCH/VID, http://dx.doi.org/10.3390/machines11050516</li>
   <li>M. A.Bravo, M. G. Molina, M. Martínez-Ledesma, B. de Haro Barbás, B. Urra, A. Elías, J. Souza, C. Villalobos, J. H. Namour, E. Ovalle, J. V. Venchiarutti, S. Blunier, J. C. Valdés-Abreu, E. Guillermo, E. Rojo, L. de Pasquale, E. Carrasco, R. Leiva, C. Castillo Rivera, A.Foppiano, M. Milla, P. R. Muñoz, M. Stepanova, J. A. Valdivia, M. Cabrera, "Ionospheric response modeling under eclipse conditions&#58; Evaluation of 14 December 2020, total solar eclipse prediction over the South American sector", Frontiers in Astronomy and Space Sciences, WOS/SCOPUS, December 2022, http://dx.doi.org/10.3389/fspas.2022.1021910</li>
   <li>S.Díaz, M. A. Díaz, E. Rajo-Iglesias, "3D-printed circular polarized cylindrical DRA using parasitic dielectric helix" 2022 IEEE USNC-URSI Radio Science Meeting (Joint with AP-S Symposium), USNC-URSI 2022 - Proceedings SCOPUS/UCH/VID, July 2023, http://dx.doi.org/10.23919/USNC-URSI52669.2022.9887464</li>	
   <li>E. Obreque, M.A. Díaz,"An Effort to Use a Solid Propellant Engine Arrangement in the Moon Soft Landing Problem", AEROSPACE ISI/SCOPUS/UCH/VID, September 2022, http://dx.doi.org/10.3390/aerospace9100540</li>
   <li>J.C. Valdés-Abreu, M.A. Díaz, M Bravo, J.C. Báez, Y. Stable-Sanchez, "Ionospheric Behavior during the 10 June 2021 Annular Solar Eclipse and Its Impact on GNSS Precise Point Positioning", REMOTE SENSING	ISI/SCOPUS/UCH/VID, June 2022, http://dx.doi.org/10.3390/rs14133119</li>
   <li>M.G.Vidal-Valladares, M.A. Díaz, "A Femto-Satellite Localization Method Based on TDOA and AOA Using Two CubeSats", February 2022, http://dx.doi.org/10.3390/rs14051101, </li>
   <li>J.C. Valdés-Abreu, M.A. Díaz, J.C. Báez, Y. Stable-Sanchez, "Effects of the 12 May 2021 Geomagnetic Storm on Georeferencing Precision", REMOTE SENSING	ISI/SCOPUS/UCH/VID, December 2021, http://dx.doi.org/10.3390/rs14010038</li>
   <li>C.E. Gonzalez, M.A. Díaz, "Nanosatellite constellation control framework using evolutionary contact plan design",  Proceedings - 8th IEEE International Conference on Space Mission Challenges for Information Technology, SMC-IT 2021	SCOPUS/UCH/VID  http://dx.doi.org/10.1109/SMC-IT51442.2021.00018, 2021, </li>
   <li>C. Garrido, M.A. Díaz, R. Rondanelli, "Automated Low-Cost LED-Based Sun Photometer for City Scale Distributed Measurements", REMOTE SENSING, November 2021ISI/SCOPUS/UCH/VID, http://dx.doi.org/10.3390/rs13224585</li>
  <li>T. Gutierrez, A. Bergel, C.E. Gonzalez, C.J. Rojas, M. A. Díaz, "Systematic Fuzz Testing Techniques on a Nanosatellite Flight Software for Agile Mission Development", IEEE ACCESS ISI/SCOPUS/UCH/VID, August 2021, http://dx.doi.org/10.1109/ACCESS.2021.3104283</li>
  <li>M.A. Díaz, C.J. Rojas, C.E. Gonzalez, E. Obreque, I.A. Portillo, "Preliminary analysis of the new space communication scenario&#58; The ground segment perspective", 2020 IEEE Congreso Bienal de Argentina, ARGENCON 2020 - 2020 IEEE Biennial Congress of Argentina, ARGENCON 2020 SCOPUS/UCH/VID, 2020, http://dx.doi.org/10.1109/ARGENCON49523.2020.9505347</li>
  <li>T. Gutierrez, A. Bergel, C.E. Gonzalez, C.J. Rojas, M.A. Díaz,"Toward applying fuzz testing techniques on the Suchai nanosatellites flight software", 2020 IEEE Congreso Bienal de Argentina, ARGENCON 2020 - 2020 IEEE Biennial Congress of Argentina, ARGENCON 2020 SCOPUS/UCH/VID, 2020, http://dx.doi.org/10.1109/ARGENCON49523.2020.9505388</li>
  <li>R. Aguirre,F. Toledo, R. Rodríguez, R. Rondanelli, N. Reyes, M.A. Díaz, "Low-Cost Ka-Band Cloud Radar System for Distributed Measurements within the Atmospheric Boundary Layer", REMOTE SENSING	ISI/SCOPUS/UCH/VID, December 2020, http://dx.doi.org/10.3390/rs12233965</li>
  <li>S.T. Gutierrez, C.I. Fuentes, M.A. Díaz, "Introducing SOST&#58; An Ultra-Low-Cost Star Tracker Concept Based on a Raspberry Pi and Open-Source Astronomy Software", IEEE ACCESS ISI/SCOPUS/UCH/VID, August 2020, http://dx.doi.org/10.1109/ACCESS.2020.3020048</li>
  <li>L. Orellana, J.Ardila-Rey, G. Avaria, M.A. Díaz, C. Pavez, R. Schurch, L. Soto, "On the Relationship Between the Electromagnetic Burst and Inductive Sensor Measurement of a Pulsed Plasma Accelerator", IEEE ACCESS ISI/SCOPUS/UCH/VID, September 2019, http://dx.doi.org/10.1109/ACCESS.2019.2941466</li>
  <li>C.E. Gonzalez, C.J. Rojas, A. Bergel, M.A. Díaz, "An Architecture-Tracking Approach to Evaluate a Modular and Extensible Flight Software for CubeSat Nanosatellites", IEEE ACCESS ISI/SCOPUS/UCH/VID, 2019, http://dx.doi.org/10.1109/ACCESS.2019.2927931</li>
  </li>C.E. Gonzalez, C.J. Rojas, A. Bergel, M.A. Díaz, "An Architecture-Tracking Approach to Evaluate a Modular and Extensible Flight Software for CubeSat Nanosatellites" IEEE ACCESS ISI/SCOPUS/UCH/VID, 2019, http://dx.doi.org/10.1109/ACCESS.2019.2927931</li>
  <li>M. Martínez-Ledesma, M.A. Díaz, "Determination of the Signal Fluctuation Threshold of the Temperature-Ion Composition Ambiguity Problem Using Monte Carlo Simulations", JOURNAL OF GEOPHYSICAL RESEARCH-SPACE PHYSICS	SCOPUS/ISI/UCH/VID, March 2019, http://dx.doi.org/10.1029/2018JA026217</li>
  <li>T. Toledo, C.Garrido, M.A. Díaz, R. Rondanelli, S. Jorquera, P. Valdivieso, "AOT Retrieval Procedure for Distributed Measurements With Low-Cost Sun Photometers", JOURNAL OF GEOPHYSICAL RESEARCH-ATMOSPHERES	ISI/SCOPUS/UCH/VID, December 2017, http://dx.doi.org/10.1002/2017JD027309</li>


